# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = dark
@accentColor = #ff0000
@background = #000

# Toolbar - black background
ToolBar.background = #000000
ToolBar.borderColor = #ff0000

# Borders - red
Button.borderColor = #ff0000
Component.focusedBorderColor = #ff0000
TabbedPane.contentAreaColor = #ff0000
TabbedPane.underlineColor = #ff0000
SplitPane.dividerForeground = #ff0000
ScrollPane.borderColor = #ff0000
TextComponent.borderColor = #ff0000
