# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = dark
@accentColor = #ff0000
@background = #000

# Toolbar - black background
ToolBar.background = #000000

# Borders - red
Component.borderColor = #ff0000
ToolBar.borderColor = #ff0000
Component.outline = #ff0000
